### ISSUE TITLE
Repo not working on local

### ISSUE THREAD

**Issue by Arjun-Lucknauth** [stackdevelopers/make-ecom-in-laravel-5.6#1]
I can't seem to get repo to work on my local. 
Steps I've done are as follows:

1.composer install
2.change env with appropriate database name
3. php artisan generate:key
4.npm install
5. php artisan migrate
I'm getting this issue, any idea how to solve this ? 

![prob](https://user-images.githubusercontent.com/40197705/45916619-2a506700-be7a-11e8-8713-d37abd567fe9.png)

**Comment by heroyouwi** [comment]
if you use php artisan migrate, you got this error, i suggest to user sample.sql in the repo, for generation of tables and rows, i tested with migrate i got the same error

**Comment by stackdevelopers** [comment]
Please download all the files and copy them into your Apache server. Create sample database and import sample.sql. Make sure to check the connectivity at .env file. Project will surely work..

**Comment by Arjun-Lucknauth** [comment]
Thanks guys, It worked great. 👍
