### ISSUE TITLE
Please update the Repo

### ISSUE THREAD

**Issue by kalpeshmote** [stackdevelopers/make-ecom-in-laravel-5.6#2]
Please update the repo with the latest code, so that repo will be in sync with youtube videos.

**Comment by stackdevelopers** [comment]
Follow below video to Download and Run E-commerce Project in Laravel 5.6 / 5.7 / 5.8  Offline (Part 1 - 100) https://youtu.be/VOpV08l9teI

Futher updates also coming soon..
